export { default as Fa } from "svelte-fa"

export {
  faAt,
  faBuildingColumns,
  faBitcoinSign,
  faCheck,
  faCirclePlus,
  faDoorOpen,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faGavel,
  faHeart,
  faHeartCrack,
  faLightbulb,
  faLock,
  faPepperHot,
  faPiggyBank,
  faPoop,
  faRightLeft,
  faRotateLeft,
  faRotateRight,
  faSeedling,
  faSquare,
  faThumbsDown,
  faThumbsUp,
  faTriangleExclamation,
  faTrophy,
  faUser,
  faXmark,
} from "../../vendor/fa.js"
